name: CI-JUDI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  # Trigger the workflow on push to master or pull request
  # to be merged in master
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: JUDI base on Julia ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      DEVITO_ARCH: ${{ matrix.cc }}
      DEVITO_LANGUAGE: "openmp"
      OMP_NUM_THREADS: 4
      GROUP: "JUDI"

    strategy:
      fail-fast: false

      matrix:
        version: ['lts', '1.7', '1.8', '1.9', '1.10']
        os: [ubuntu-latest]
        arch: ['x64']
        cc: ['gcc-12']

        include:
          - os: macos-15
            version: '1'
            arch: ARM64
            cc: clang

    steps:
      - name: Checkout JUDI
        uses: actions/checkout@v4

      - name: Setup julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - name: Setup clang for osx
        if: runner.os == 'macOS'
        run: |
          brew install llvm libomp
          echo "/opt/homebrew/bin:/opt/homebrew/opt/llvm/bin" >> $GITHUB_PATH

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Set julia python
        run: |
          echo "JULIA_PYTHONCALL_EXE=$(which python3)" >> $GITHUB_ENV
          echo "JULIA_CONDAPKG_BACKEND=\"Null\"" >> $GITHUB_ENV
          python3 -m pip install devito[tests,extras]@git+https://github.com/devitocodes/devito.git
          JULIA_PYTHONCALL_EXE=$(which python3) JULIA_CONDAPKG_BACKEND="Null" julia -e 'using Pkg;Pkg.add("PythonCall");Pkg.build("PythonCall")'

      - name: Build JUDI
        uses: julia-actions/julia-buildpkg@latest

      - name: Run tests
        uses: julia-actions/julia-runtest@latest
        with:
          annotate: true

      - uses: julia-actions/julia-processcoverage@v1

      - uses: codecov/codecov-action@v4
        with:
          file: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}