name: Publish docs via GitHub Pages

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    tags: '*'

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    env:
      CI: "true"

    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - uses: julia-actions/setup-julia@latest
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Set julia python
        run: |
          echo "PYTHON=$(which python3)" >> $GITHUB_ENV
          echo "PYCALL_JL_RUNTIME_PYTHON=$(which python3)" >> $GITHUB_ENV
          echo "JULIA_PYTHONCALL_EXE=$(which python3)" >> $GITHUB_ENV
          echo "JULIA_CONDAPKG_BACKEND=Null" >> $GITHUB_ENV

      - name: Build JUDI
        uses: julia-actions/julia-buildpkg@latest

      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'

      - name: Build python doc
        run: |
          pip install --upgrade pip
          pip install sphinx sphinx-markdown-builder sphinx-markdown-parser devito matplotlib
          # pip install "sphinx==3.1.0" "MarkupSafe==2.0.1" "jinja2<3.1" "sphinxcontrib-devhelp==1.0.5"
          make clean
          make markdown
          mv _build/markdown/pysource.md ../../docs/src/pysource.md
        working-directory: src/pydocs/

      - name: Build doc
        run: |
          pip install --upgrade jupyter Pygments
          for f in *.ipynb;do jupyter nbconvert --to markdown --output-dir='../../docs/src/tutorials' $f; done
        working-directory: examples/notebooks/

      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
        run: julia --project=docs/ docs/make.jl
